// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* MyService_method_names[] = {
  "/MyService/call",
};

std::unique_ptr< MyService::Stub> MyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MyService::Stub> stub(new MyService::Stub(channel, options));
  return stub;
}

MyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_call_(MyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MyService::Stub::call(::grpc::ClientContext* context, const ::MyRequest& request, ::MyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MyRequest, ::MyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_call_, context, request, response);
}

void MyService::Stub::async::call(::grpc::ClientContext* context, const ::MyRequest* request, ::MyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MyRequest, ::MyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, std::move(f));
}

void MyService::Stub::async::call(::grpc::ClientContext* context, const ::MyRequest* request, ::MyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MyResponse>* MyService::Stub::PrepareAsynccallRaw(::grpc::ClientContext* context, const ::MyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::MyResponse, ::MyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_call_, context, request);
}

::grpc::ClientAsyncResponseReader< ::MyResponse>* MyService::Stub::AsynccallRaw(::grpc::ClientContext* context, const ::MyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccallRaw(context, request, cq);
  result->StartCall();
  return result;
}

MyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MyService::Service, ::MyRequest, ::MyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MyRequest* req,
             ::MyResponse* resp) {
               return service->call(ctx, req, resp);
             }, this)));
}

MyService::Service::~Service() {
}

::grpc::Status MyService::Service::call(::grpc::ServerContext* context, const ::MyRequest* request, ::MyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


